#FROM nginx
FROM roura/tengine
#FROM roura/tengine-proxy
MAINTAINER Jazav <name@gmail.com>

    # Copy bakerydemo nginx configuration file
COPY bakerydemo-nginx.conf /etc/nginx/conf.d/bakerydemo-nginx.conf